<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

$om = \Magento\Framework\App\ObjectManager::getInstance();

$hawkBanner = $om->get(\HawkSearch\Proxy\Block\Banner::class);
$helper = $om->create(\HawkSearch\Proxy\Helper\Data::class);
$request = $om->create(\Magento\Framework\App\Request\Http::class);

$args = array_merge($request->getParams(), ['output' => 'custom', 'hawkitemlist' => 'json']);
$helper->setUri($args);
$helper->setClientIp($request->getClientIp());
$helper->setClientUa($om->create(\Magento\Framework\HTTP\Header::class)->getHttpUserAgent());
$helper->setIsHawkManaged(true);
?>
<div id="hawkbannertop" class="bannerTop"><?= /* @noEscape */ $hawkBanner->getBannerTop() ?></div>
<div id="hawkitemlist"><?= /* @noEscape */ $block->getChildHtml('product_list') ?></div>
<div id="hawkbannerbottom" class="bannerBottom"><?= /* @noEscape */ $hawkBanner->getBannerBottom() ?></div>';
