<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

$om=\Magento\Framework\App\ObjectManager::getInstance();

$hawkBanner=$om->get('HawkSearch\Proxy\Model\Banner');
 
$helper=$om->create('HawkSearch\Proxy\Helper\Data');
$request=$om->create('Magento\Framework\App\Request\Http');

$args = array_merge($request->getParams(), array('output' => 'custom', 'hawkitemlist'=>'json'));
			$helper->setUri($args);
			$helper->setClientIp($request->getClientIp());
			$helper->setClientUa($om->create('\Magento\Framework\HTTP\Header')->getHttpUserAgent());

			

			$helper->setIsHawkManaged(true);






?>
<div id="hawkbannertop" class="bannerTop"><?php echo $hawkBanner->getBannerTop()?></div><div id="hawkitemlist"><?php echo $this->getChildHtml('product_list')?></div><div id="hawkbannerbottom" class="bannerBottom"><?php echo $hawkBanner->getBannerBottom() ?></div>';
