<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
 /** @var $this Magento\Framework\View\Element\Template */
/** @var $hawkBanner HawkSearch\Proxy\Model\Banner */
$om=\Magento\Framework\App\ObjectManager::getInstance();
$hawkBanner=$om->get('HawkSearch\Proxy\Model\Banner');
?>
<div id="hawkbannertop" class="bannerTop">
    <?php echo $hawkBanner->getFeaturedTop() ?>
	<?php echo $hawkBanner->getBannerTop() ?></div>
<div id="hawkitemlist">
	<?php echo $this->getChildHtml(); ?></div>
<div id="hawkbannerbottom" class="bannerBottom">
    <?php echo $hawkBanner->getFeaturedBottom() ?>
	<?php echo $hawkBanner->getBannerBottom() ?></div>
<div id="hawkbannerbottom2" class="bannerBottom">
	<?php echo $hawkBanner->getBannerBottom2() ?>
    <?php echo $hawkBanner->getFeaturedBottom2() ?>
</div>
