<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
 /** @var $block HawkSearch\Proxy\Block\HawkItems */
?>
<div id="hawkbannertop" class="bannerTop">
    <?= /* @noEscape */ $block->getBanner()->getFeaturedTop() ?>
    <?= /* @noEscape */ $block->getBanner()->getBannerTop() ?></div>
<div id="hawktoptext"><?= /* @noEscape */ $block->getTopText() ?></div>
<div id="hawkitemlist">
    <?= /* @noEscape */ $block->getChildHtml(); ?>
</div>
<?= /* @noEscape */ $block->getClickTracking(); ?>
<div id="hawkbannerbottom" class="bannerBottom">
    <?= /* @noEscape */ $block->getBanner()->getFeaturedBottom() ?>
    <?= /* @noEscape */ $block->getBanner()->getBannerBottom() ?></div>
<div id="hawkbannerbottom2" class="bannerBottom">
    <?= /* @noEscape */ $block->getBanner()->getBannerBottom2() ?>
    <?= /* @noEscape */ $block->getBanner()->getFeaturedBottom2() ?>
</div>
