<?php
/**
 * Copyright (c) 2018 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/** @var $block \HawkSearch\Proxy\Block\Tabbed */
$increment = 1;
$tabs = $block->getTabs();

?>

<div>
    <div id="hawktitle"><?php echo $block->getTitle() ?></div>
    <div id="hawkbannertop"
         class="bannerTop"> <?php echo $block->getBanner()->getFeaturedTop() ?><?php echo $block->getBanner()->getBannerTop() ?></div>
    <div id="hawktoptext"><?php echo $block->getTopText(); ?></div>
    <div id="hawkrelated"><?php echo $block->getRelated() ?></div>
    <?php if(!empty($tabs)) { echo sprintf('<div id="hawktabs">%s</div>', $tabs); } ?>
    <div id="hawktoppager"><?php echo $block->getTopPager(); ?></div>
    <div id="hawkitemlist">
        <?php echo $block->getChildHtml('hawksearch_tabbed_items'); ?>
    </div>
    <div id="hawkbottompager"><?php echo $block->getBottomPager(); ?></div>
    <div id="hawkbannerbottom"
         class="bannerBottom"> <?php echo $block->getBanner()->getFeaturedBottom() ?><?php echo $block->getBanner()->getBannerBottom() ?></div>
    <div id="hawkbannerbottom2"
         class="bannerBottom"> <?php echo $block->getBanner()->getBannerBottom2() ?><?php echo $block->getBanner()->getFeaturedBottom2() ?></div>
</div>
