<?php
/**
 * Copyright (c) 2019 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/** @var Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection $pac */

/** @var $block HawkSearch\Proxy\Block\Footer */
?>
<script type="text/javascript">
    <?php if($block->isTrackingV2()): ?>
    (function (HawkSearch) {
        HawkSearch.BaseUrl = '<?php echo $block->getBaseUrl(); ?>';
        HawkSearch.HawkUrl = '<?php echo $block->getHawkUrlWithEngine(); ?>';
        HawkSearch.TrackingUrl = '<?php echo $block->getTrackingUrl(); ?>';
        HawkSearch.RecommenderUrl = '<?php echo $block->getRecommenderUrl(); ?>';
        HawkSearch.ClientGuid = '<?php echo $block->getTrackingKey(); ?>';
        if ('http:' == document.location.protocol) {
            HawkSearch.BaseUrl = HawkSearch.BaseUrl.replace('https://', 'http://');
            HawkSearch.HawkUrl = HawkSearch.HawkUrl.replace('https://', 'http://');
            HawkSearch.TrackingUrl = HawkSearch.TrackingUrl.replace('https://', 'http://');
            HawkSearch.RecommenderUrl = HawkSearch.RecommenderUrl.replace('https://', 'http://');
        }
        if ('https:' == document.location.protocol) {
            HawkSearch.BaseUrl = HawkSearch.BaseUrl.replace('http://', 'https://');
            HawkSearch.HawkUrl = HawkSearch.HawkUrl.replace('http://', 'https://');
            HawkSearch.TrackingUrl = HawkSearch.TrackingUrl.replace('http://', 'https://');
            HawkSearch.RecommenderUrl = HawkSearch.RecommenderUrl.replace('http://', 'https://');
        }
    }(window.HawkSearch = window.HawkSearch || {}));
    <?php else: ?>
    (function (HawkSearch) {
        HawkSearch.BaseUrl = '<?php echo $block->getBaseUrl(); ?>';
        HawkSearch.TrackingUrl = '<?php echo $block->getHawkUrlWithEngine(); ?>';
        if ('http:' == document.location.protocol) {
            HawkSearch.BaseUrl = HawkSearch.BaseUrl.replace('https://', 'http://');
            HawkSearch.TrackingUrl = HawkSearch.TrackingUrl.replace('https://', 'http://');
        }
        if ('https:' == document.location.protocol) {
            HawkSearch.BaseUrl = HawkSearch.BaseUrl.replace('http://', 'https://');
            HawkSearch.TrackingUrl = HawkSearch.TrackingUrl.replace('http://', 'https://');
        }
    }(window.HawkSearch = window.HawkSearch || {}));
    <?php endif; ?>

    require(["jquery", "hawksearch" ], function ($) {
        <?php foreach($block->getSearchBoxes() as $sbid) : ?>
            HawkSearch.suggestInit('#<?php echo $sbid; ?>', {
                lookupUrlPrefix: HawkSearch.HawkUrl + '<?php echo $block->getAutosuggestParams() ?>',
                hiddenDivName: '<?php echo $block->getHiddenDivName() ?>',
                isAutoWidth: true
            });
        <?php endforeach; ?>

        HawkSearch.bindClickTracking = function(data) {
            var items = $('#hawkitemlist');
            for(var row in data) {
                    items.find('a[href="' + data[row]["url"] + '"]').click({
                        tid: data[row]["tid"],
                        idx: data[row]["i"],
                        sku: data[row]["sku"]
                    }, function (e) {
                    return HawkSearch.link(e, e.data.tid, e.data.idx, e.data.sku, 0);
                });
            }
        };
        HawkSearch.origProcessFacets = HawkSearch.processFacets;
        HawkSearch.processFacets = function(hash, json, queryGuid, backbutton) {
            HawkSearch.origProcessFacets(hash, json, queryGuid, backbutton);
            var data = $(json.html).find('#hawktrackingdata').data('tracking');
            HawkSearch.bindClickTracking(data);
        };
        HawkSearch.bindClickTracking($(document).find('#hawktrackingdata').data('tracking'));

        <?php if($block->getRecommendationsActive()) : ?>
        $(document).on('hawksearch:track', function(e, data) {
            if(data.pageload.hasOwnProperty("context")) {
                for(key in data.pageload.context) {
                    HawkSearch.Context.add(key, data.pageload.context[key]);
                }
            }
            HawkSearch.Tracking.track("pageload", {pageType: data.pageload.pageType});
        });
        <?php endif; ?>
    });
    <?php if($block->getRecommendationsActive()) : ?>
    require(["jquery", "hawksearch", "domReady"], function ($){
        let s = 'script[type="text/x-hawk-track"]';
        let nodes = $(s);
        if (typeof nodes[0] !== 'undefined') {
            let data = JSON.parse(nodes[0].textContent);
            $(document).trigger('hawksearch:track', data);
        }
    });
    <?php endif; ?>
</script>