<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/** @var $helper \HawkSearch\Proxy\Helper\Data */
$om=\Magento\Framework\App\ObjectManager::getInstance();

$helper=$om->get('HawkSearch\Proxy\Helper\Data');
?>
<script type="text/javascript">
    (function (HawkSearch, undefined) {
        HawkSearch.BaseUrl = '<?php echo $helper->getBaseUrl(); ?>';
        HawkSearch.TrackingUrl = '<?php echo $helper->getTrackingUrl(); ?>';
        if ('https:' == document.location.protocol) {
            HawkSearch.BaseUrl = HawkSearch.BaseUrl.replace('http://', 'https://');
            HawkSearch.TrackingUrl = HawkSearch.TrackingUrl.replace('http://', 'https://');
        }
    }(window.HawkSearch = window.HawkSearch || {}));
    require(["hawksearch"], function() {
        HawkSearch.initAutoSuggest = function () {
            HawkSearch.suggestInit('#search', {
                lookupUrlPrefix: HawkSearch.TrackingUrl +
                '/?fn=ajax&f=GetSuggestions',
                hiddenDivName: '',
                isAutoWidth: true
            });
        };
    });
</script>