<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
 
 /** @var $block \HawkSearch\Proxy\Block\Html */
/** @var $hawkBanner \HawkSearch\Proxy\Model\Banner */
$om=\Magento\Framework\App\ObjectManager::getInstance();
$hawkBanner=$om->get('HawkSearch\Proxy\Model\Banner');
?>

<div>
  <div id="hawkmetarobots"><?php echo $block->getMetaRobots() ?></div>
  <div id="hawkheadertitle"><?php echo $block->getHeaderTitle() ?></div>
  <div id="hawkmetadescription"><?php echo $block->getMetaDescription() ?></div>
  <div id="hawkmetakeywords"><?php echo $block->getMetaKeywords() ?></div>
  <div id="hawkrelcanonical"><?php echo $block->getRelCanonical() ?></div>
  <div id="hawktoptext"><?php echo $block->getTopText() ?></div>
  <div id="hawkitemlist"><?php echo $block->getItemList() ?></div>
  <div id="hawkexplain"></div>
  <div id="hawksmartbug"></div>
  <div id="hawkrelated"><?php echo $block->getRelated() ?></div>
  <div id="hawkfacets"><?php echo $block->getFacets() ?></div>
  <div id="hawkbannertop" class="bannerTop"> <?php echo $hawkBanner->getFeaturedTop() ?> <?php echo $hawkBanner->getBannerTop() ?></div>
  <div id="hawkbannerlefttop" class="bannerLeftTop"><?php echo $hawkBanner->getBannerLeftTop() ?></div>
  <div id="hawkbannerleftbottom" class="bannerLeftBottom"><?php echo $hawkBanner->getBannerLeftBottom() ?></div>
  <div id="hawkbannerbottom" class="bannerBottom"> <?php echo $hawkBanner->getFeaturedBottom() ?> <?php echo $hawkBanner->getBannerBottom() ?></div>
  <div id="hawkbannerbottom2" class="bannerBottom"> <?php echo $hawkBanner->getBannerBottom2() ?> <?php echo $hawkBanner->getFeaturedBottom2() ?></div>
  <div id="hawkbreadcrumb"><?php echo $block->getBreadCrumb() ?></div>
  <div id="hawktitle"><?php echo $block->getTitle() ?></div>
</div>
