<?php
/**
 * Copyright (c) 2023 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

use HawkSearch\Proxy\Block\Html;

/** @var $block Html */
$tabs = $block->getTabs();
?>

<div>
    <div id="hawkmetarobots"><?= /* @noEscape */
        $block->getMetaRobots() ?></div>
    <div id="hawkheadertitle"><?= /* @noEscape */
        $block->getHeaderTitle() ?></div>
    <div id="hawkmetadescription"><?= /* @noEscape */
        $block->getMetaDescription() ?></div>
    <div id="hawkmetakeywords"><?= /* @noEscape */
        $block->getMetaKeywords() ?></div>
    <div id="hawkrelcanonical"><?= /* @noEscape */
        $block->getRelCanonical() ?></div>
    <div id="hawktoptext"><?= /* @noEscape */
        $block->getTopText() ?></div>
    <div id="hawkitemlist"><?= /* @noEscape */
        $block->getItemList() ?></div>
    <?= /* @noEscape */
    $block->getHawkTrackingData(); ?>
    <div id="hawkexplain"></div>
    <div id="hawksmartbug"></div>
    <div id="hawkrelated"><?= /* @noEscape */
        $block->getRelated() ?>
    </div>
    <?php if ($block->isShowFacets()): ?>
    <div id="hawkfacets" class="block">
    <?php else: ?>
    <div id="hawkfacets" style="display: none">
    <?php endif; ?>
        <?= /* @noEscape */ $block->getFacets() ?>
    </div>


    <?= $block->getChildHtml('hawksearch_html_additional') ?>

    <div id="hawkbreadcrumb"><?= /* @noEscape */
        $block->getBreadCrumb() ?></div>
    <div id="hawktitle"><?= /* @noEscape */
        $block->getTitle() ?></div>
    <?php if ($block->getTabbedContent()) : ?>
        <div id="hawktoppager"><?= /* @noEscape */
            $block->getTopPager(); ?></div>
        <div id="hawkbottompager"><?= /* @noEscape */
            $block->getBottomPager(); ?></div>
    <?php endif; ?>
    <?php if ($tabs) : ?>
        <?= /* @noEscape */ sprintf('<div id="hawktabs">%s</div>', $tabs); ?>
    <?php endif;?>
</div>
