<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/** @var $helper \HawkSearch\Proxy\Helper\Data */
$om=\Magento\Framework\App\ObjectManager::getInstance();

$helper=$om->get('HawkSearch\Proxy\Helper\Data');
?>
<!-- Hawk Search Header Includes -->
<script type="text/javascript">
	document.write(unescape("%3Clink rel='stylesheet' type='text/css' href='<?php echo $helper->getTrackingUrl(); ?>/includes/hawksearch.css'%3E%3C/link%3E"));
</script>