<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/**
 * Cache template
 *
 * @var $block \HawkSearch\Proxy\Block\System\Config\Sync
 */
$locked = $block->isSyncLocked();
?>
<div>
    <div id="hawk_synchrinize_result" class="message-validation hidden"></div>
    <button type="button"
            id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span>
    </button>
    <div id="forcesyncwrap" class="hidden">
        <input type="checkbox" value="forcesync" id="<?php echo $block->getHtmlId() ?>_forcesync" name="forcesync" /> force sync
    </div>
    <input type="checkbox" value="overwrite" id="<?php echo $block->getHtmlId() ?>_overwrite" name="overwrite" /> overwrite all
</div>

<script>
    require(['prototype'], function() {
        var locked = <?php echo $locked ? 'true' : 'false'; ?>;
        var b = $('<?php echo $block->getHtmlId() ?>');
        var force = $('<?php echo $block->getHtmlId() ?>_forcesync');
        var forcewrap = $('forcesyncwrap');
        var overwrite = $('<?php echo $block->getHtmlId() ?>_overwrite');
        if(locked) {
            b.disable();
            force.enable();
            forcewrap.removeClassName('hidden');
            force.observe('click', function(event) {
                if(this.checked) {
                    b.enable();
                } else {
                    b.disable();
                }
            });
        } else {
            b.enable();
            force.disable();
        }
        b.observe('click', function(event) {
            var isForce = force.checked;
            var isOverwrite = overwrite.checked;
            new Ajax.Request('<?php echo $this->getInternUrl() ?>', {
                parameters: {force: isForce, overwrite: isOverwrite},
                onSuccess: function(transport) {
                    var resp = transport.responseText.evalJSON();
                    var respEl = $('hawk_synchrinize_result');
                    if(resp.error) {
                        respEl.innerHTML = resp.error;
                    } else if(resp.message) {
                        respEl.innerHTML = resp.message;
                    } else {
                        respEl.innerHTML = 'Unexpected response';
                    }
                    respEl.removeClassName('hidden');
                    b.disabled = true;
                    b.addClassName('disabled');
                    b.stopObserving('click');
                },
                onFailure: function(response, rHeader) {
                    alert('There has been an error. Please contact your developer');
                    b.disabled = true;
                    b.addClassName('disabled');
                    b.stopObserving('click');
                },
                onException: function(request, exception) {
                    alert('There has been an error. Please contact your developer');
                    b.disabled = true;
                    b.addClassName('disabled');
                    b.stopObserving('click');
                }
            })
        });

    });

</script>
