<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/**
 * Cache template
 * @var $block Sync
 */

$nextScheduledId        = $block->getNextScheduledId();
$nextScheduledTimestamp = $block->getNextScheduledTimestamp();
?>
<div>
    <a href="<?= $block->escapeHtml( $block->getInternUrl() ) ?>">
        <button type="button" id="<?php echo $block->getHtmlId() ?>">
            <span><?php echo $block->escapeHtml( $block->getButtonLabel() ); ?></span>
        </button>
    </a>
    <?php if ( $nextScheduledId ): ?>
        <div id="hawk_datagenerate_next_scheduled" style="margin-top: 8px">
            <p>Next feed generation at <?= $nextScheduledTimestamp ?> (CRON ID: <?= $nextScheduledId ?>)</p>
        </div>
    <?php endif; ?>
</div>
