<?php
/**
 * Copyright (c) 2023 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

use HawkSearch\Proxy\ViewModel\ProductListToolbar;

?>
<?php
/** @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar */
/** @var ProductListToolbar $toolbarViewModel */
$toolbarViewModel = $block->getData('toolbarViewModel');
if (!($toolbarViewModel instanceof ProductListToolbar)) {
    return;
}
?>
<div id="hawktoppager">
    <?= $toolbarViewModel->getTopToolbarHtml() ?>
</div>
